<?php

return [
    'surat-keterangan-domisili' => [
        'label' => 'Surat Keterangan Domisili',
        'fields' => [
            'nama' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'pattern' => '[A-Za-z\s]+',
                'rules' => 'required|string|max:255',
            ],
            'nik' => [
                'label' => 'NIK',
                'type' => 'text',
                'required' => true,
                'inputmode'=> 'numeric',
                'oninput' => "this.value=this.value.replace(/[^0-9]/g,'')",
                'pattern' => "\d{16}",
                'minlength' => '16',
                'maxlength' => '16',
                'title' => 'NIK harus 16 digit angka',
                'rules' => 'required|numeric|digits:16',
            ],
            'tempat_tanggal_lahir' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true,
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],
            'agama' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
            ],
            'pekerjaan' => [
                'label' => 'Pekerjaan',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'alamat' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => false,
                'rules' => 'nullable|string|max:500',
            ],
        ],
    ],

    'surat-keterangan-tidak-mampu' => [
        'label' => 'Surat Keterangan Tidak Mampu (SKTM)',
        'fields' => [
            'nama' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'pattern' => '[A-Za-z\s]+',
                'rules' => 'required|string|max:255',
            ],
            'nik' => [
                'label' => 'NIK',
                'type' => 'text',
                'required' => true,
                'inputmode'=> 'numeric',
                'oninput' => "this.value=this.value.replace(/[^0-9]/g,'')",
                'pattern' => "\d{16}",
                'minlength' => '16',
                'maxlength' => '16',
                'title' => 'NIK harus 16 digit angka',
                'rules' => 'required|numeric|digits:16',
            ],
            'tempat_tanggal_lahir' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true,
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],
            'agama' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
            ],
            'pekerjaan' => [
                'label' => 'Pekerjaan',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'alamat' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
        ],
    ],

    'surat-keterangan-usaha' => [
        'label' => 'Surat Keterangan Usaha',
        'fields' => [
            'nama' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'pattern' => '[A-Za-z\s]+',
                'rules' => 'required|string|max:255',
            ],
            'nik' => [
                'label' => 'NIK',
                'type' => 'text',
                'required' => true,
                'inputmode'=> 'numeric',
                'oninput' => "this.value=this.value.replace(/[^0-9]/g,'')",
                'pattern' => "\d{16}",
                'minlength' => '16',
                'maxlength' => '16',
                'title' => 'NIK harus 16 digit angka',
                'rules' => 'required|numeric|digits:16',
            ],
            'tempat_tanggal_lahir' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true,
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],
            'alamat' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
            'nama_usaha' => [
                'label' => 'Nama Usaha',
                'type' => 'text',
                'required' => false,
                'rules' => 'nullable|string|max:255',
            ],
            'jenis_usaha' => [
                'label' => 'Jenis Usaha',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
            'alamat_usaha' => [
                'label' => 'Alamat Usaha',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
        ],
    ],

    'surat-keterangan-belum-menikah' => [
        'label' => 'Surat Keterangan Belum Menikah',
        'fields' => [
            'nama' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'pattern' => '[A-Za-z\s]+',
                'rules' => 'required|string|max:255',
            ],
            'nik' => [
                'label' => 'NIK',
                'type' => 'text',
                'required' => true,
                'inputmode'=> 'numeric',
                'oninput' => "this.value=this.value.replace(/[^0-9]/g,'')",
                'pattern' => "\d{16}",
                'minlength' => '16',
                'maxlength' => '16',
                'title' => 'NIK harus 16 digit angka',
                'rules' => 'required|numeric|digits:16',
            ],
            'tempat_tanggal_lahir' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true,
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],
            'agama' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
            ],
            'pekerjaan' => [
                'label' => 'Pekerjaan',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'kewarganegaraan' => [
                'label' => 'Warga Negara',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:50',
            ],
            'alamat' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
        ],
    ],

    'surat-keterangan-pengantar' => [
        'label' => 'Surat Keterangan Pengantar',
        'fields' => [
            'nama' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'pattern' => '[A-Za-z\s]+',
                'rules' => 'required|string|max:255',
            ],
            'nik' => [
                'label' => 'NIK',
                'type' => 'text',
                'required' => true,
                'inputmode'=> 'numeric',
                'oninput' => "this.value=this.value.replace(/[^0-9]/g,'')",
                'pattern' => "\d{16}",
                'minlength' => '16',
                'maxlength' => '16',
                'title' => 'NIK harus 16 digit angka',
                'rules' => 'required|numeric|digits:16',
            ],
            'tempat_tanggal_lahir' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true,
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],
            'agama' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
            ],
            'pekerjaan' => [
                'label' => 'Pekerjaan',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'alamat' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
            'tujuan_pengantar' => [
                'label' => 'Tujuan',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
        ],
    ],

    'surat-keterangan-keluarga' => [
        'label' => 'Surat Keterangan Keluarga',
        'fields' => [
            'nama_pemohon' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
            'nik_pemohon' => [
                'label' => 'NIK',
                'type' => 'text',
                'required' => true,
                'inputmode'=> 'numeric',
                'oninput' => "this.value=this.value.replace(/[^0-9]/g,'')",
                'pattern' => "\d{16}",
                'minlength' => '16',
                'maxlength' => '16',
                'title' => 'NIK harus 16 digit angka',
                'rules' => 'required|numeric|digits:16',
            ],
            'tempat_tanggal_lahir_pemohon' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true, 
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin_pemohon' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true, 
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],            
            'agama_pemohon' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
            ],
            'pekerjaan_pemohon' => [
                'label' => 'Pekerjaan',
                'type' => 'text',
                'required' => true, 
                'rules' => 'required|string|max:100',
            ],            
            'alamat_pemohon' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
            'nama_anggota_keluarga' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
            'nik_anggota_keluarga' => [
                'label' => 'NIK',
                'type' => 'text',
                'required' => true,
                'inputmode'=> 'numeric',
                'oninput' => "this.value=this.value.replace(/[^0-9]/g,'')",
                'pattern' => "\d{16}",
                'minlength' => '16',
                'maxlength' => '16',
                'title' => 'NIK harus 16 digit angka',
                'rules' => 'required|numeric|digits:16',
            ],
            'tempat_tanggal_lahir_anggota_keluarga' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true, 
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin_anggota_keluarga' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true, 
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],            
            'agama_anggota_keluarga' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
            ],
            'pekerjaan_anggota_keluarga' => [
                'label' => 'Pekerjaan',
                'type' => 'text',
                'required' => true, 
                'rules' => 'required|string|max:100',
            ],            
            'alamat_anggota_keluarga' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
        ],
    ],

    'surat-keterangan-kematian' => [
        'label' => 'Surat Keterangan Kematian',
        'fields' => [
            'nama' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
            'tempat_tanggal_lahir' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true,
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],
            'agama' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
            ],
            'alamat' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
            'hari_tanggal_kematian' => [
                'label' => 'Hari/Tanggal',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|date',
            ],
            'jam' => [
                'label' => 'Jam',
                'type' => 'text',
                'required' => false,
                'rules' => 'nullable|string|max:10',
            ],
            'sebab_kematian' => [
                'label' => 'Sebab Kematian',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
            'tempat_kematian' => [
                'label' => 'Tempat Kematian',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
        ],
    ],

    'surat-keterangan-kelahiran' => [
        'label' => 'Surat Keterangan Kelahiran',
        'fields' => [
                'nama' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
            'tempat_tanggal_lahir' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true,
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],
                'agama' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
        ],
            'alamat' => [
                'label' => 'Alamat',
                'type' => 'textarea',
                'required' => true,
                'rules' => 'required|string|max:500',
            ],
            'nama_ayah' => [
                'label' => 'Nama Ayah Kandung',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
            'nama_ibu' => [
                'label' => 'Nama Ibu Kandung',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:255',
            ],
            'anak_ke' => [
                'label' => 'Anak Ke',
                'type' => 'number',
                'required' => true,
                'rules' => 'required|numeric',
            ],
        ],
    ],

    'surat-keterangan-berkelakuan-baik' => [
        'label' => 'Surat Keterangan Berkelakuan Baik',
        'fields' => [
            'nama' => [
                'label' => 'Nama',
                'type' => 'text',
                'required' => true,
                'pattern' => '[A-Za-z\s]+',
                'rules' => 'required|string|max:255',
            ],
            'nik' => [
                'label' => 'NIK',
                'type' => 'text',
                'required' => true,
                'inputmode'=> 'numeric',
                'oninput' => "this.value=this.value.replace(/[^0-9]/g,'')",
                'pattern' => "\d{16}",
                'minlength' => '16',
                'maxlength' => '16',
                'title' => 'NIK harus 16 digit angka',
                'rules' => 'required|numeric|digits:16',
            ],
            'tempat_tanggal_lahir' => [
                'label' => 'Tempat/Tanggal Lahir',
                'type' => 'text',
                'required' => true,
                'rules' => 'required|string|max:100',
            ],
            'jenis_kelamin' => [
                'label' => 'Jenis Kelamin',
                'type' => 'select',
                'required' => true,
                'options' => ['Laki-laki', 'Perempuan'],
                'rules' => 'required|in:Laki-laki,Perempuan',
            ],
            'agama' => [
                'label' => 'Agama',
                'type' => 'select',
                'required' => true,
                'options' => ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'],
                'rules' => 'required|in:Islam,Kristen,Katolik,Hindu,Buddha,Konghucu',
        ],
        'status_perkawinan' => [
            'label' => 'Status Perkawinan',
            'type' => 'select',
            'required' => true,
            'options' => ['Belum Kawin', 'Kawin', 'Cerai Hidup', 'Cerai Mati'],
            'rules' => 'required|in:Belum Kawin,Kawin,Cerai Hidup,Cerai Mati',
        ],
        'pekerjaan' => [
            'label' => 'Pekerjaan',
            'type' => 'text',
            'required' => true,
            'rules' => 'required|string|max:100',
        ],
        'alamat' => [
            'label' => 'Alamat',
            'type' => 'textarea',
            'required' => true,
            'rules' => 'required|string|max:500',
        ],
            'keterangan' => [
            'label' => 'Keterangan',
            'type' => 'textarea',
            'required' => true,
            'rules' => 'required|string|max:500',
        ],
    ],
],
'surat-keterangan-kepemilikan-rumah' => [
    'label' => 'Surat Keterangan Kepemilikan Rumah',
    'fields' => [
        'nama' => [
            'label' => 'Nama',
            'type' => 'text',
            'required' => true,
            'rules' => 'required|string|max:255',
        ],
        'nik' => [
            'label' => 'NIK',
            'type' => 'text',
            'required' => true,
            'rules' => 'required|numeric|digits:16',
        ],
        'tempat_tanggal_lahir' => [
            'label' => 'Tempat/Tanggal Lahir',
            'type' => 'text',
            'required' => true,
            'rules' => 'required|string|max:100',
        ],
        'pekerjaan' => [
            'label' => 'Pekerjaan',
            'type' => 'text',
            'required' => true,
            'rules' => 'required|string|max:100',
        ],
        'alamat' => [
            'label' => 'Alamat',
            'type' => 'textarea',
            'required' => true,
            'rules' => 'required|string|max:500',
        ],
        'alamat_rumah' => [
            'label' => 'Alamat Rumah yang Dimiliki',
            'type' => 'textarea',
            'required' => true,
            'rules' => 'required|string|max:500',
        ],
        'luas_tanah' => [
            'label' => 'Luas Tanah (m²)',
            'type' => 'text',
            'required' => false,
            'rules' => 'nullable|numeric|min:0',
        ],
        'luas_bangunan' => [
            'label' => 'Luas Bangunan (m²)',
            'type' => 'text',
            'required' => false,
            'rules' => 'nullable|numeric|min:0',
        ],
    ],
],
];
